#!/usr/bin/env bash

HDFS_TEXT_FILES_HOME="/dev/equipo5/JediAnalytics/"

hdfs dfs -rm -r ${HDFS_TEXT_FILES_HOME}CAT_TIPO_CLT
hdfs dfs -rm -r ${HDFS_TEXT_FILES_HOME}CAT_TIPO_CONTAC
hdfs dfs -rm -r ${HDFS_TEXT_FILES_HOME}CAT_TIPO_DOCUM
hdfs dfs -rm -r ${HDFS_TEXT_FILES_HOME}CLT_CONTACTABILIDAD
hdfs dfs -rm -r ${HDFS_TEXT_FILES_HOME}CLT_DATOS
hdfs dfs -rm -r ${HDFS_TEXT_FILES_HOME}CLT_DOCUMENTACION
hdfs dfs -rm -r ${HDFS_TEXT_FILES_HOME}CLT_RELACION_CTA_CLTE
hdfs dfs -rm -r ${HDFS_TEXT_FILES_HOME}CLT_SUCURSAL
